#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_blog_by_Id:
    path: /api/getprocutInforamtion/{id}
    controller: App\Controller\ListController::getProductInfo
    methods: GET
